spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project2022
    username: postgres
    password: admin

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: off

application:
  jwt:
    secret-key: thisBetterBeTheStrongestSecuredKeyEverOrElseImScrewed
    token-prefix: 'Bearer '
    token-expiration-after-ms: 1800000 #30min

server:
  port:
    8080